sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v 

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && test "$TRAVIS_PULL_REQUEST" = "false" 
    && sh .travis/deploy_heroku.sh

notifications:
  email:
    on_success: never
